name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'


categories:
  - title: 'üí• Breaking Changes'
    labels:
      - breaking-change
  - title: 'üí° New Features'
    labels:
      - feature
      - enhancement
  - title: 'üêû Bug Fixes'
    labels:
      - bug
      - fix
      - bugfix
  - title: '‚öôÔ∏è Technical Debt'
    labels:
      - refactor
  - title: 'üìù Documentation'
    labels:
      - documentation

change-template: "- (#$NUMBER) $TITLE by @$AUTHOR"

no-changes-template: 'No significant changes'

template: |
  ## üöÄ Release

  ### What's Changed
  $CHANGES

  ---

  ### üê≥ Docker Images

  - **[qubership-pipegene](https://github.com/$OWNER/$REPOSITORY/pkgs/container/qubership-pipegene)** - `ghcr.io/netcracker/qubership-pipegene:$RESOLVED_VERSION`
  - **[qubership-envgene](https://github.com/$OWNER/$REPOSITORY/pkgs/container/qubership-envgene)** - `ghcr.io/netcracker/qubership-envgene:$RESOLVED_VERSION`
  - **[qubership-effective-set-generator](https://github.com/$OWNER/$REPOSITORY/pkgs/container/qubership-effective-set-generator)** - `ghcr.io/netcracker/qubership-effective-set-generator:$RESOLVED_VERSION`
  - **[qubership-instance-repo-pipeline](https://github.com/$OWNER/$REPOSITORY/pkgs/container/qubership-instance-repo-pipeline)** - `ghcr.io/netcracker/qubership-instance-repo-pipeline:$RESOLVED_VERSION`
  - **[qubership-gsf-instance](https://github.com/$OWNER/$REPOSITORY/pkgs/container/qubership-gsf-instance)** - `ghcr.io/netcracker/qubership-gsf-instance:$RESOLVED_VERSION`

  ---

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
