name: "application-3"
registryName: "{{ appdefs.overrides['com.example:application-3'].registryName | default('registry-3') }}"
artifactId: "application-3"
groupId: "org.qubership"
supportParallelDeploy: true
deployParameters: {}
technicalConfigurationParameters: {}