name: "[NOT USE - GSF build]: Build GSF package"

on:
  workflow_dispatch:
    inputs:
      build-gsf-instance:
        description: 'Build GSF Instance image'
        required: false
        default: true
        type: boolean

env:
  REGISTRY: ghcr.io
  CI_PROJECT_DIR: ${{ github.workspace }}

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-gsf-instance:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.build-gsf-instance == 'true')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      custom_tag: ${{ steps.build-gsf-instance.outputs.custom_tag }}
      branch_tag: ${{ steps.build-gsf-instance.outputs.branch_tag }}
      timestamp: ${{ steps.build-gsf-instance.outputs.timestamp }}
      branch_latest_tag: ${{ steps.build-gsf-instance.outputs.branch_latest_tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Qubership PipeGene Docker Image
      uses: ./.github/actions/build-gsf-instance
      id: build-gsf-instance
      with:
        registry: ${{ env.REGISTRY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
